# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "57bcaf5aa29cf9a42a13486444852b438ecdbcc7"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
git-tree-sha1 = "9e2f36d3c96a820c678f2f1f1782582fcf685bae"
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"
version = "1.9.1"

[[deps.FoucaultBase]]
deps = ["DelimitedFiles"]
path = "."
uuid = "aaf8cd2f-76e1-45d4-97a8-038d3664b746"
version = "0.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
version = "1.11.0"
